name: Deploy to VM

on:
  push:
    branches:
      - master  # Change this to your main branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # You can use a different OS if necessary

    steps:
      - name: Deploy to VM
        run: |
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.PRIVATE_KEY }} vivo@101.188.67.134 "cd /home/anilmasapeta/wp-anil && git pull"
