name: Access server
on: push
jobs:
  access_server:
    name: Access server
    runs-on: ubuntu-latest
    steps:
      - name: Create a file
        uses: appleboy/ssh-action@master
        with:
          host: 192.168.2.10
          username: vivo
          key: ${{ secrets.KEY }}
          script: echo hello world > /home/anilmasapeta/hello.txt
          
