name: Access server
on: push
jobs:
  access_server:
    name: Access server
    runs-on: ubuntu-latest
    steps:
      - name: Create a file
        uses: Anil-55/ssh-action@master
        with:
          host: 192.168.2.10
          username: vivo
          key: ${{ secrets.PRIVATE_KEY }}
          script: echo hello world > hello.txt
