name: Deploy to Remote Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH into remote server and run command
        uses: appleboy/ssh-action@master
        with:
          host: 192.168.2.10
          username: vivo
          key: ${{ secrets.KEY }}
          port: 22
          script: |
            cd /home/anilmasapeta/wp-anil
            touch file23
           
           
